### ISSUE TITLE
RSS not working for many sites

### ISSUE THREAD

**Issue by kevin-stuart** [erickok/transdroid#269]
The RSS feeds of many sites are not working for some reason. For example:

- https://rarbg.com/rss.php
- https://kat.cr/?rss=1

They can be opened fine in the browser.

**Comment by erickok** [comment]
Due to new style SSL certificates that were not yet supported. Should be fixed in 57e33b4ce727a7fbe29deef0005df426439b77df.

**Comment by buttie** [comment]
It's still not working in 2.5.6. I found following entries in catlog:
`02-16 15:24:16.370 E/ImageLoader(24591): http://grabicon.com/icon?origin=www.transdroid.org&domain=https://rarbg.to/rssdd.php?categories=41
02-16 15:24:16.370 E/ImageLoader(24591): java.io.FileNotFoundException: http://grabicon.com/icon?origin=www.transdroid.org&domain=https://rarbg.to/rssdd.php?categories=41`

**Comment by adelolmo** [comment]
Also got the same error in the log as @buttie 
In my case I get "405 Not Allowed" when trying the url in the computer browser.
http://grabicon.com/icon?origin=www.transdroid.org&domain=http://showrss.info/user/18370.rss?magnets=true&namespaces=false&name=clean&quality=null&re=yes

**Comment by adelolmo** [comment]
I was curious about grabicon.com and checked their website. It turns out that it's not a free service after the first 30 days trial period. Then again, there's a limit of requests per day in the different payment packages (http://grabicon.com/pricing).
Is it grabicon.com the best option? 
Here they suggest two other options: http://stackoverflow.com/questions/22842262/an-alternative-for-http-g-etfv-co-url-favicon-services#answer-27899580
But i don't know any of them.

**Comment by kevin-stuart** [comment]
On the website there is still only version 2.5.6, the same version is on GitHub releases. How are new versions with fixes released? The issue was filed two months ago and although it is fixed in the source, maybe new builds should be published more often? Maybe there should be automatic builds with Travis?

Alternatively, maybe there should be an easy way to build pre-release versions? When I tried building versions earlier, it was tedious because of different signing keys and identical package names. Although this is still not as nice as official builds would be.
